version: '3.1'

services:
  enzo-bot:
    image: dorru/enzo-ts:1.2.3
    container_name: enzo-ts
    hostname: enzo-ts
    volumes:
      - ./mounted-files/config/enzo_tsc_config.json:/enzo_ts/_var/enzo_tsc/profile_default/enzo_tsc_config.json
      - ./mounted-files/logs/enzo_tsl:/enzo_ts/_var/enzo_tsl/profile_default/logs
      - ./mounted-files/logs/enzo_tsc:/enzo_ts/_var/enzo_tsc/profile_default/logs
      - ./mounted-files/cache:/root/enzo_ts_cache
